[package]
name = "hivemind"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full", "net", "rt-multi-thread", "macros"] }
anyhow = "1.0"
axum = "0.7"
containerd-client = "0.3"
tonic = "0.9"
futures = "0.3"
